# Lazy loading
source ~/.zshlazy

# Editor
export VISUAL=nvim
export EDITOR="$VISUAL"

# Golang
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:~/go/bin
export GOPATH=~/go

# User Bin
export PATH=$PATH:~/bin
