# global config
if [[ -o login ]]; then
    ZSH_TMUX_AUTOSTART=true
fi


ANTIGEN_PATH=~/.dotfiles
source $ANTIGEN_PATH/bin/antigen/antigen.zsh

# oh-my-zsh
antigen use oh-my-zsh

# oh-my-zsh plugins
antigen bundles <<EOBUNDLES
    common-aliases
    docker
    gpg-agent
    golang
    git
    tmux
EOBUNDLES

# further plugins
antigen bundles <<EOBUNDLES
    zsh-users/zsh-syntax-highlighting
    zsh-users/zsh-completions
    zsh-users/zsh-autosuggestions
EOBUNDLES

# Theme
antigen theme gallifrey

# Apply
antigen apply

# Aliases
source ~/.zshalias
